server:
  port: 8001

spring:
  application:
    name: psd-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EllsaG/psd-config-ymls
          clone-on-start: true
          default-label: master
          search-paths:
            - '{application}'