server:
  port: 8001

spring:
  application:
    name: test-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EllsaG/test-config-ymls.git
          clone-on-start: true
          default-label: master
          search-paths:
            - '{application}'